on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run clippy
    env: 
      DATABASE_URL: postgres:://localhost:5432?dbname=demo&user=runner&password=password
    services:
      postgres:
        image: postgres
        env:
          DATABASE_URL: postgres:://localhost:5432?dbname=demo&user=runner&password=password
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: password
          POSTGRES_DB: demo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install sqlx cli
        run: cargo install sqlx-cli
      - name: Migrate
        run: sqlx migrate run
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  check-typo:
    runs-on: ubuntu-latest
    name: Run typos
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install typos
        run: cargo install typos-cli
      - name: Run typos
        run: typos
